version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "15432:5432"
    volumes:
      - flask-postgres-volume:/var/lib/postgresql/data
    env_file:
      - .env


volumes:
  flask-postgres-volume:
    driver: local
